# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{process_pool}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Adam Pohorecki"]
  s.date = %q{2010-01-20}
  s.email = %q{adam@pohorecki.pl}
  s.extra_rdoc_files = [
    "LICENSE",
     "README"
  ]
  s.files = [
    ".gitignore",
     "Gemfile",
     "LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "lib/init.rb",
     "lib/process_pool.rb",
     "lib/simple_logger.rb",
     "lib/simple_queue.rb",
     "process_pool.gemspec",
     "test/process_pool_test.rb",
     "test/simple_queue_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/psyho/process_pool}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{ProcessPool with interchangeable job queue backends for Ruby}
  s.test_files = [
    "test/process_pool_test.rb",
     "test/simple_queue_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json>, [">= 0"])
    else
      s.add_dependency(%q<json>, [">= 0"])
    end
  else
    s.add_dependency(%q<json>, [">= 0"])
  end
end

